DELETE FROM TBL_ITEM;

insert into TBL_ITEM values ('Parallel Integer Sorting and Simulation Amongst CRCW Models','Sanjeev Saxena','book','1996','106','tad','MT Publisher','0');
insert into TBL_ITEM values ('Pattern Matching in Trees and Nets','Hans-Ulrich Simon','book','1983','117','tad','MT Publisher','0');
insert into TBL_ITEM values ('NPcomplete Problems Simplified on Tree Schemas','Oded Shmueli','book','1983','128','tad','MT Publisher','0');
insert into TBL_ITEM values ('On the Power of Chain Rules in Context Free Grammars','Norbert Blum','book','1982','138','tad','MT Publisher','0');
insert into TBL_ITEM values ('Schnelle Multiplikation von Polynomen uumlber Koumlrpern der Charakteristik 2','Arnold Sch&ouml;nhage','book','1977','151','tad','MT Publisher','0');
insert into TBL_ITEM values ('A characterization of rational D0L power series','Juha Honkala','book','2011','159','tad','MT Publisher','0');
insert into TBL_ITEM values ('The Derivation of Systolic Implementations of Programs','Christian Lengauer','book','1987','171','tad','MT Publisher','0');
insert into TBL_ITEM values ('Fifo Nets Without Order Deadlock','Annie Choquet','book','1988','183','tad','MT Publisher','0');
insert into TBL_ITEM values ('On the Complementation Rule for Multivalued Dependencies in Database Relations','Joachim Biskup','book','1978','194','tad','MT Publisher','0');
insert into TBL_ITEM values ('Equational weighted tree transformations','George Rahonis','book','2012','206','tad','MT Publisher','0');
insert into TBL_ITEM values ('Merged processes a new condensed representation of Petri net behaviour','Walter Vogler','book','2006','220','tad','MT Publisher','0');
insert into TBL_ITEM values ('Verifying a simplification of mutual exclusion by LycklamaHadzilacos','Wim H. Hesselink','book','2013','231','tad','MT Publisher','0');
insert into TBL_ITEM values ('A ThreeStage Construction for Multiconnection Networks','Christian Ronse','book','1983','242','tad','MT Publisher','0');
insert into TBL_ITEM values ('The Expressive Power of Delay Operators in SCCS','Prakash Panangaden','book','1991','253','tad','MT Publisher','0');
insert into TBL_ITEM values ('Calculi for Interaction','Robin Milner','book','1996','264','tad','MT Publisher','0');
insert into TBL_ITEM values ('A Synthesis of Several Sorting Algorithms','John Darlington','book','1978','275','tad','MT Publisher','0');
insert into TBL_ITEM values ('A Workload Model Representative of Static and Dynamic Characteristics','Giuseppe Serazzi','book','1986','287','tad','MT Publisher','0');
insert into TBL_ITEM values ('Gray visiting Motzkins','Vincent Vajnovszki','book','2002','298','tad','MT Publisher','0');
insert into TBL_ITEM values ('Trace and failurebased semantics for responsiveness','Richard M&uuml;ller 0001','book','2014','111','tad','MT Publisher','0');
insert into TBL_ITEM values ('Branching Processes in the Analysis of the Heights of Trees','Luc Devroye','book','1987','122','tad','MT Publisher','0');
insert into TBL_ITEM values ('Least Upper Bound on the Cost of Optimum Binary Search Trees','K. C. Tan','book','1972','137','tad','MT Publisher','0');
insert into TBL_ITEM values ('The Mathematical Analysis of the Computer System Modeled as a Two Stage Cyclic Queue','William R. Franta','book','1976','146','tad','MT Publisher','0');
insert into TBL_ITEM values ('Invariants Composition and Substitution','Ekkart Kindler','book','1995','160','tad','MT Publisher','0');
insert into TBL_ITEM values ('Maximum Entropy and the i','Demetres D. Kouvatsos','book','1986','168','tad','MT Publisher','0');
insert into TBL_ITEM values ('Abstraction and Performance in the Design of Parallel Programs An Overview of the SAT Approach','Christian Lengauer','book','2000','180','tad','MT Publisher','0');
insert into TBL_ITEM values ('A theory of structural stationarity in the i','Roland Meyer','book','2009','191','tad','MT Publisher','0');
insert into TBL_ITEM values ('Hex ist PSPACEvollstaumlndig','Stefan Reisch','book','1981','202','tad','MT Publisher','0');
insert into TBL_ITEM values ('Evolutionary Systems A Language Generating Device Inspired by Evolving Communities of Cells','Victor Mitrana','book','2000','213','tad','MT Publisher','0');
insert into TBL_ITEM values ('Relational structures model of concurrency','Ryszard Janicki','book','2008','224','tad','MT Publisher','0');
insert into TBL_ITEM values ('On an Equivalence between Continuation and Stack Semantics','Bruce Russell','book','1977','238','tad','MT Publisher','0');
insert into TBL_ITEM values ('Nonterminals Versus Homomorphisms in Defining Languages for Some Classes of Rewriting Systems','Grzegorz Rozenberg','book','1974','250','tad','MT Publisher','0');
insert into TBL_ITEM values ('A Note on the Density of Inherently Ambiguous Contextfree Languages','Rainer Kemp','book','1980','258','tad','MT Publisher','0');
insert into TBL_ITEM values ('Time Lower Bounds for Parallel Sorting on a MeshConected Processor Array','Yoshihide Igarashi','book','1989','269','tad','MT Publisher','0');
insert into TBL_ITEM values ('Computational Algorithms for Networks of Queues with Rejection Blocking','Horst von Brand','book','1989','281','tad','MT Publisher','0');
insert into TBL_ITEM values ('Compositional Refinements in Multiple Blackboard Systems','Carlo Montangero','book','1995','297','tad','MT Publisher','0');
insert into TBL_ITEM values ('Special issue on Combining Compositionality and Concurrency part 1','Ernst-R&uuml;diger Olderog','book','2015','107','tad','MT Publisher','0');
insert into TBL_ITEM values ('Automatic verification of concurrent systems using a formulabased compositional approach','Antonella Santone','book','2002','118','tad','MT Publisher','0');
insert into TBL_ITEM values ('On Removing the Machine from the Language','Eric C. R. Hehner','book','1978','129','tad','MT Publisher','0');
insert into TBL_ITEM values ('Complete Problems for Space Bounded Subclasses of NP','Ivan Hal Sudborough','book','1985','141','tad','MT Publisher','0');
insert into TBL_ITEM values ('Efficient controller synthesis for a fragment of MTLsub','Guangyuan Li','book','2014','155','tad','MT Publisher','0');
insert into TBL_ITEM values ('Two Notions of Correctness and Their Relation to Testing','Dana Angluin','book','1982','167','tad','MT Publisher','0');
insert into TBL_ITEM values ('Best Huffman Trees','George Markowsky','book','1981','177','tad','MT Publisher','0');
insert into TBL_ITEM values ('Behandlung verschiedener INTEGERDarstellungen durch optimierende Compiler','Manfred P. Stadel','book','1981','187','tad','MT Publisher','0');
insert into TBL_ITEM values ('The Parsing Problem for Affix Grammars','David A. Watt','book','1977','200','tad','MT Publisher','0');
insert into TBL_ITEM values ('On Efficient Entreeings','Derick Wood','book','1993','210','tad','MT Publisher','0');
insert into TBL_ITEM values ('Persistence of Vector Replacement Systems is Decidable','Ernst W. Mayr','book','1981','221','tad','MT Publisher','0');
insert into TBL_ITEM values ('Implementing Daubechies Wavelet Transform with Weighted Finite Automata','Simant Dube','book','1997','232','tad','MT Publisher','0');
insert into TBL_ITEM values ('Functional Behavior in Data Spaces','Thomas N. Hibbard','book','1978','244','tad','MT Publisher','0');
insert into TBL_ITEM values ('Inductive Completion with Retracts','William P. R. Mitchell','book','1988','254','tad','MT Publisher','0');
insert into TBL_ITEM values ('Sometime  Always  Recursion  Always on the Equivalence of the Intermittent and Invariant Assertions Methods for Proving Inevitability Properties of Programs','Radhia Cousot','book','1987','266','tad','MT Publisher','0');
insert into TBL_ITEM values ('Complete Parameterized Families of Job Scheduling Strategies','J. H. Hine','book','1977','281','tad','MT Publisher','0');
insert into TBL_ITEM values ('Modelling higherorder dual nondeterminacy','Malcolm Tyrrell','book','2008','290','tad','MT Publisher','0');
insert into TBL_ITEM values ('Dispatcher Primitives for the Construction of Operating System Kernels','J&uuml;rgen Nehmer','book','1975','104','tad','MT Publisher','0');
insert into TBL_ITEM values ('A Recursive Second Order Initial Algebra Specification of Primitive Recursion','Karl Meinke','book','1994','123','tad','MT Publisher','0');
insert into TBL_ITEM values ('ContextFree Graph Languages of Bounded Degree are Generated by Apex Graph Grammars','George Leih','book','1994','136','tad','MT Publisher','0');
insert into TBL_ITEM values ('Worst Case Performance of Weighted Buddy Systems','Pradip K. Srimani','book','1987','148','tad','MT Publisher','0');
insert into TBL_ITEM values ('Contextual Nets','Francesca Rossi','book','1995','164','tad','MT Publisher','0');
insert into TBL_ITEM values ('COSY  A System Specification Language Based on Paths and Processes','M. W. Shields','book','1979','174','tad','MT Publisher','0');
insert into TBL_ITEM values ('Applying relation algebra and Rel View to solve problems on orders and lattices','Rudolf Berghammer','book','2008','184','tad','MT Publisher','0');
insert into TBL_ITEM values ('Eliminating Unit Productions from LR Parsers','David Pager','book','1977','195','tad','MT Publisher','0');
insert into TBL_ITEM values ('Attribute Reevaluation in OPTRAN','Reinhard Wilhelm','article','1988','208','seller1','MT Publisher','0');
insert into TBL_ITEM values ('On Parallel Integer Sorting','Sandeep Sen','article','1992','220','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Domain Independence and the Relational Calculus','Jianwen Su','article','1994','232','seller1','MT Publisher','0');
insert into TBL_ITEM values ('MultiGranularity Locking for Nested Transactions A Proof Using a Possibilities Mapping','Alan Fekete','article','1996','244','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Bounded Quantification and Relations Recognizable by Finite Automata','Teuvo Laurinolli','article','1978','255','seller1','MT Publisher','0');
insert into TBL_ITEM values ('A Complete Algebraic Characterization of Behavioral Subtyping','Don Pigozzi','article','2000','266','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Minimum Feedback Vertex Sets in Cocomparability Graphs and Convex Bipartite Graphs','Maw-Shang Chang','article','1997','278','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Behavioural Approaches to Algebraic Specifications A Comparative Study','Teodor Knapik','article','1994','291','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Instruction sequence processing operators','C. A. Middelburg','article','2012','103','seller1','MT Publisher','0');
insert into TBL_ITEM values ('What is Failure An Approach to Constructive Negation','Wlodzimierz Drabent','article','1995','118','seller1','MT Publisher','0');
insert into TBL_ITEM values ('STG decomposition strategies in combination with unfolding','Ralf Wollowski','article','2009','129','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Quad Trees A Data Structure for Retrieval on Composite Keys','Jon Louis Bentley','article','1974','144','seller1','MT Publisher','0');
insert into TBL_ITEM values ('On the Number of Relational Operators Necessary to Compute Certain Functions of Real Variables','Alfred Schmitt','article','1983','152','seller1','MT Publisher','0');
insert into TBL_ITEM values ('A Study of Queueing Networks with Deterministic Service and Application to Computer Networks','Guy Pujolle','article','1976','166','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Explaining the Wheel Sieve','Paul Pritchard','article','1982','174','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Another Polynomial Homomorphism','Robert T. Moenck','article','1976','184','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Variance Reduction Techniques for the Simulation of Markov Process','Philip Heidelberger','article','1980','194','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Decomposition of Graphs and Monotone Formula Size of Homogeneous Functions','Siegfried Bublitz','article','1986','204','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Deterministic pushdownCDsystems of stateless deterministic R1automata','Friedrich Otto','article','2013','216','seller1','MT Publisher','0');
insert into TBL_ITEM values ('On the Synchronization in Parallel Communicating Grammar Systems','Gheorghe Paun','article','1993','227','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Weakly ContextSensitive Languages as Model for Programming Languages','P. F. Schuler','article','1974','241','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Rules of Inference for Procedure Calls','George W. Ernst','article','1977','252','seller1','MT Publisher','0');
insert into TBL_ITEM values ('The Construction of Operator Interfaces Based on Logical Input Devices','G&uuml;nther E. Pfaff','article','1983','260','seller1','MT Publisher','0');
insert into TBL_ITEM values ('High Level Tree Transducers and Iterated Pushdown Tree Transducers','Heiko Vogler','article','1988','271','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Gobang ist PSPACEvollstaumlndig','Stefan Reisch','article','1980','282','seller1','MT Publisher','0');
insert into TBL_ITEM values ('A note on autodense related languages','Kuo-Hsiang Chen','article','2010','295','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Solving HPP and SAT by P Systems with Active Membranes and Separation Rules','Artiom Alhazov','article','2006','107','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Optimizing the Costs of Hierarchical Quorum Consensus','Kavindra Malik','article','1996','119','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Recursive Petri nets','Denis Poitrenaud','article','2007','131','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Multitype Multiprogramming Models','George Humfeld','article','1976','146','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Automatic Correction of SyntaxErrors in Programming Languages','J.-P. L&eacute;vy','article','1974','157','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Representation and uniformization of algebraic transductions','Sheng Yu','article','2007','167','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Concurrent Bisimulations in Petri Nets','Lucia Pomello','article','1991','181','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Enhanced prefetching and caching strategies for single and multidisk systems','Markus B&uuml;ttner','article','2005','192','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Recording the Use of Memory in RightBoundary Grammars and PushDown Automata','Grzegorz Rozenberg','article','1988','205','seller1','MT Publisher','0');
insert into TBL_ITEM values ('State space axioms for Tsystems','Raymond R. Devillers','article','2015','217','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Extended multi bottomup tree transducers','Andreas Maletti','article','2009','230','seller1','MT Publisher','0');
insert into TBL_ITEM values ('The Clean Termination of Iterative Programs','Andrzej Blikle','article','1981','241','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Infinite Proof Rules for Loops','Fred Kr&ouml;ger','article','1980','251','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Nonfinite Axiomatizability of the Equational Theory of Shuffle','Michael Bertol','article','1998','262','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Running a job on a collection of partly available machines with online restarts','Johannes A. La Poutr&eacute;','article','2001','274','seller1','MT Publisher','0');
insert into TBL_ITEM values ('Data Refinement by Calculation','Paul H. B. Gardiner','proceeding','1990','286','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Program Refinement in Fair Transition Systems','Ambuj K. Singh','proceeding','1993','297','seller2','MT Publisher','0');
insert into TBL_ITEM values ('A Functional Model for Describing and Reasoning About Time Behaviour of Computing Systems','Nicolas Halbwachs','proceeding','1986','109','seller2','MT Publisher','0');
insert into TBL_ITEM values ('MNets An Algebra of HighLevel Petri Nets with an Application to the Semantics of Concurrent Programming Languages','Elisabeth Pelz','proceeding','1998','124','seller2','MT Publisher','0');
insert into TBL_ITEM values ('On the LookAhead Problem in Lexical Analysis','Wuu Yang','proceeding','1995','139','seller2','MT Publisher','0');
insert into TBL_ITEM values ('The maximum gain of increasing the number of preemptions in multiprocessor scheduling','H&aring;kan Lennerstad','proceeding','2009','149','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Data Encodings and Their Costs','Arnold L. Rosenberg','proceeding','1978','160','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Hierarchies of Complete Problems','Zvi Galil','proceeding','1976','170','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Ein Vollstaumlndigkeitssatz fuumlr Programme und Schaltkreise','Volker Claus','proceeding','1971','183','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Typebased information flow analysis for the picalculus','Naoki Kobayashi 0001','proceeding','2005','191','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Sur une Conjecture de S Greibach','Jean Berstel','proceeding','1974','205','seller2','MT Publisher','0');
insert into TBL_ITEM values ('A Conservation Law for GGm Queueing Systems','Gunter Bolch','proceeding','1978','214','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Applications of Efficient Mergeable Heaps for Optimization Problems on Trees','Zvi Galil','proceeding','1980','224','seller2','MT Publisher','0');
insert into TBL_ITEM values ('ContextFree Graph Grammars and Concatenation of Graphs','Jan Joris Vereijken','proceeding','1997','235','seller2','MT Publisher','0');
insert into TBL_ITEM values ('On a Class of Recursive Procedures and Equivalent Iterative Ones','Teruo Hikita','proceeding','1979','246','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Algorithms for Fast Evaluation of Boolean Expressions','Allen Reiter','proceeding','1975','260','seller2','MT Publisher','0');
insert into TBL_ITEM values ('A Comparison of Two Synchronizing Concepts','Per Brinch Hansen','proceeding','1972','271','seller2','MT Publisher','0');
insert into TBL_ITEM values ('How to Calculate Symmetries of Petri Nets','Karsten Schmidt 0004','proceeding','2000','280','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Nonterminals Homomorphisms and Codings in Different Variations of OLSystems  I Deterministic Systems','Sven Skyum','proceeding','1974','297','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Recognizability of graph and pattern languages','Antonios Kalampakas','proceeding','2006','106','seller2','MT Publisher','0');
insert into TBL_ITEM values ('The Synthesis Problem of Petri Nets','Wolfgang Reisig','proceeding','1996','118','seller2','MT Publisher','0');
insert into TBL_ITEM values ('A Binary Operation on Trees and an Initial Algebra Characterization for Finite Tree Types','Wolfgang Merzenich','proceeding','1979','129','seller2','MT Publisher','0');
insert into TBL_ITEM values ('On weighted firstorder logics with discounting','George Rahonis','proceeding','2014','140','seller2','MT Publisher','0');
insert into TBL_ITEM values ('A Characterization of Contextfree String Languages by Directed Nodelabel Controlled Graph Grammars','Grzegorz Rozenberg','proceeding','1981','152','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Demonic angelic and unbounded probabilistic choices in sequential programs','Carroll Morgan','proceeding','2001','163','seller2','MT Publisher','0');
insert into TBL_ITEM values ('An Efficiency Preorder for Processes','Matthew Hennessy','proceeding','1992','175','seller2','MT Publisher','0');
insert into TBL_ITEM values ('On the Generalization of Higman and Kruskals Theorems to Regular Languages and Rational Trees','Stefano Varricchio','proceeding','2000','187','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Modeling Splits in File Structures','Ricardo A. Baeza-Yates','proceeding','1989','198','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Languages Accepted by Systolic YTree Automata Structural Characterizations','Domenico Parente','proceeding','1992','212','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Synchronized regular expressions','Marisa Venturini Zilli','proceeding','2003','226','seller2','MT Publisher','0');
insert into TBL_ITEM values ('On regular tree languages and deterministic pushdown automata','Borivoj Melichar','proceeding','2009','238','seller2','MT Publisher','0');
insert into TBL_ITEM values ('A Modal Logic for Message Passing Processes','Xinxin Liu','proceeding','1995','254','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Maintaining Range Trees in Secondary Memory Part I Partitions','Marc J. van Kreveld','proceeding','1990','265','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Does indirect addressing matter  A note','Michael Brand','proceeding','2012','276','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Reasoning Algebraically about Loops','Joakim von Wright','proceeding','1999','288','seller2','MT Publisher','0');
insert into TBL_ITEM values ('A Model of a Time Sharing Virtual Memory System Solved Using Equivalence and Decomposition Methods','Alexandre Brandwajn','proceeding','1974','102','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Trace Nets and Process Automata','Philippe Darondeau','proceeding','1995','111','seller2','MT Publisher','0');
insert into TBL_ITEM values ('A Principle of Independence for Binary Tree Searching','Leonidas J. Guibas','proceeding','1974','126','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Optimal DivideandConquer to Compute Measure and Contour for a Set of IsoRectangles','Ralf Hartmut G&uuml;ting','proceeding','1984','134','seller2','MT Publisher','0');
insert into TBL_ITEM values ('The Paging Drum Queue A Uniform Perspective and Further Results','Qui Hoon Choo','proceeding','1984','145','seller2','MT Publisher','0');
insert into TBL_ITEM values ('The Undecidability of the Unification and Matching Problem for Canonical Theories','Steffen H&ouml;lldobler','proceeding','1987','156','seller2','MT Publisher','0');
insert into TBL_ITEM values ('The Programming Language Pascal','Niklaus Wirth','proceeding','1971','170','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Semantics calculi and analysis for objectoriented specifications','Burkhart Wolff','proceeding','2009','179','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Inhibitionsfelder','Hermann K.-G. Walter','proceeding','1972','193','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Head and state hierarchies for unary multihead finite automata','Matthias Wendlandt','proceeding','2014','204','seller2','MT Publisher','0');
insert into TBL_ITEM values ('On the Number of ActiveOperations Needed to Compute the Discrete Fourier Transform','Bernhard Mescheder','proceeding','1980','215','seller2','MT Publisher','0');
insert into TBL_ITEM values ('The stuttering principle revisited','Jan Strejcek','proceeding','2005','226','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Redundant Proofs of NonInterference in LevinGries CSP Program Proofs','Thomas P. Murtagh','proceeding','1987','237','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Lazy Structure Sharing for Query Optimization','Robert Endre Tarjan','proceeding','1995','254','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Fair ambients','Yuxi Fu','proceeding','2007','262','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Concurrent Access to Data','Norbert Ramsperger','proceeding','1977','276','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Relaxed redblack trees with group updates','Kim S. Larsen','proceeding','2002','284','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Generation of Efficient i','Masataka Sassa','proceeding','1986','296','seller2','MT Publisher','0');
insert into TBL_ITEM values ('A Markovian queue with varying number of servers and applications to the performance comparison of HSDPA user equipment','L&aacute;szl&oacute; Pap','proceeding','2011','110','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Priority ConflictFree Petri Nets','Hsu-Chun Yen','proceeding','1998','121','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Optimum Multiway Search Trees','Derick Wood','proceeding','1980','134','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Characterization of all Optimal Networks for a Simultaneous Computation of AND and NOR','Martin Seysen','proceeding','1984','145','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Parallel Integer Sorting Using Small Operations','Pramod K. Varshney','proceeding','1995','161','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Stochastic cooperative distributed grammar systems and random graphs','Martin Neh&eacute;z','proceeding','2003','170','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Performance Evaluation of Fork and Join Synchronization Primitives','Tadeusz Czach&oacute;rski','proceeding','1987','182','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Some properties of the disjunctive languages contained in i','Y. S. Tsai','proceeding','2011','194','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Systolic Automata for VLSI on Balanced Trees','Arto Salomaa','proceeding','1982','207','seller2','MT Publisher','0');
insert into TBL_ITEM values ('A new natural structural congruence in the picalculus with replication','Tjalling Gelsema','proceeding','2004','218','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Optimal Multiprogramming','Rajan Suri','proceeding','1976','236','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Classes of Systolic YTree Automata and a Comparison with Systolic Trellis Automata','Davide Sangiorgi','proceeding','1992','246','seller2','MT Publisher','0');
insert into TBL_ITEM values ('On RealTime Cellular Automata and Trellis Automata','Karel Culik II','proceeding','1984','258','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Transformational Design of RealTime Systems Part I From Requirements to Program Specifications','Ernst-R&uuml;diger Olderog','proceeding','1999','269','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Performance Preorder and Competitive Equivalence','Marco Roccetti','proceeding','1997','282','seller2','MT Publisher','0');
insert into TBL_ITEM values ('A Survey of Normal Form Covers for Context Free Grammars','Anton Nijholt','proceeding','1980','293','seller2','MT Publisher','0');
insert into TBL_ITEM values ('A Note on Synthesis and Classification of Sorting Algorithms','Kung-Kiu Lau','proceeding','1989','103','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Liveness of a mutex algorithm in a fair process algebra','Walter Vogler','proceeding','2009','116','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Another Look at the Longest Ascending Subsequence Problem','Paul Pritchard','proceeding','1981','127','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Complexity Theory and the Operational Structure of Algebraic Programming Systems','J. V. Tucker','proceeding','1982','138','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Models for Reactivity','Amir Pnueli','proceeding','1993','149','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Axioms for Generalized Graphs Illustrated by a CantorBernstein Proposition','Tjalling Gelsema','proceeding','1998','161','seller2','MT Publisher','0');
insert into TBL_ITEM values ('A Proof System for Distributed Processes','Neelam Soundararajan','proceeding','1988','173','seller2','MT Publisher','0');
insert into TBL_ITEM values ('Finite State Relational Programs','Giora Slutzki','proceeding','1982','184','seller2','MT Publisher','0');
insert into TBL_ITEM values ('A Gap Between the Actual Complexity of Permutations and Their Entropy Defined by Stoszlig','Stefan Reisch','proceeding','1981','195','seller2','MT Publisher','0');